import { readFile, rename, writeFile } from "node:fs/promises";

import sharp from "sharp";

import type { PhotoAsset, PhotoDimensions } from "../content/types";

export function assertExpectedPhotoDimensions(
  asset: Pick<PhotoAsset, "key" | "width" | "height">,
  actual: PhotoDimensions,
  sourceLabel: string,
): void {
  const hasExpectedWidth = asset.width !== undefined;
  const hasExpectedHeight = asset.height !== undefined;

  if (hasExpectedWidth !== hasExpectedHeight) {
    throw new Error(
      `[images] ${asset.key} must provide both width and height as an optional size assertion, or omit both`,
    );
  }
  if (
    hasExpectedWidth &&
    (actual.width !== asset.width || actual.height !== asset.height)
  ) {
    throw new Error(
      `[images] ${sourceLabel} is ${actual.width}×${actual.height} after EXIF orientation, but its optional size assertion says ${asset.width}×${asset.height}`,
    );
  }
}

export async function readPhotoDimensions(
  sourcePath: string,
): Promise<PhotoDimensions> {
  const metadata = await sharp(sourcePath).metadata();
  const orientedSize = metadata.autoOrient ?? metadata;

  if (!orientedSize.width || !orientedSize.height) {
    throw new Error(`could not read oriented dimensions from ${sourcePath}`);
  }

  return { width: orientedSize.width, height: orientedSize.height };
}

export function renderPhotoDimensionsManifest(
  dimensionsByKey: ReadonlyMap<string, PhotoDimensions>,
): string {
  const records = [...dimensionsByKey.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([key, dimensions]) =>
        `  ${JSON.stringify(key)}: { width: ${dimensions.width}, height: ${dimensions.height} },`,
    )
    .join("\n");

  return `// Generated by \`npm run images:build\`. Do not edit by hand.\n\nexport const photoDimensions = {\n${records}\n};\n`;
}

export async function writePhotoDimensionsManifest(
  outputPath: string,
  dimensionsByKey: ReadonlyMap<string, PhotoDimensions>,
): Promise<void> {
  const nextContents = renderPhotoDimensionsManifest(dimensionsByKey);

  try {
    if (await readFile(outputPath, "utf8") === nextContents) return;
  } catch {
    // The first image build creates the generated module.
  }

  const temporaryPath = `${outputPath}.tmp`;
  await writeFile(temporaryPath, nextContents, "utf8");
  await rename(temporaryPath, outputPath);
}
